/**
 * functionMapExport.ts — 把 functionExecSpec 编译成 Java 执行测试消费的 JSON。
 *
 * JSON 里带的是**编译器当前真实输出**的 XML 片段（不是手写模板），Java 侧
 * 原样拼进 ruleset 执行——TS 编译器输出漂移时，同步测试先红，Java 执行
 * 测试随后兜底。单一事实源在 functionMap.ts。
 */

import { parseCondition, parseAction } from './expressionParser';
import { EXEC_CASES, EXEC_LIBS, type ExecCase, type AssertType } from './functionExecSpec';
import { allFuncs } from './functionMap';

export interface ExportedCase {
  rea: string;
  position: ExecCase['position'];
  /** value/action: then 内嵌 XML；condition: if 内嵌 XML */
  xml: string;
  facts?: Record<string, Record<string, unknown>>;
  path?: string;
  assert: { type: AssertType; value?: string | number };
}

export interface ExportedFunctionMap {
  note: string;
  cases: ExportedCase[];
}

function compile(c: ExecCase): string {
  const call = `${c.rea}(${c.argsRea.join(', ')})`;
  if (c.position === 'condition') {
    // 内置 Boolean 函数裸 atom 隐式 == TRUE；自定义返回类型未知，显式比较
    return parseCondition(c.compareTrue ? `${call} == TRUE` : call, EXEC_LIBS);
  }
  if (c.position === 'action') {
    return parseAction(call, EXEC_LIBS);
  }
  return parseAction(`FlightInfo.result = ${call}`, EXEC_LIBS);
}

export function buildFunctionMapExport(): string {
  const exported: ExportedFunctionMap = {
    note: 'Generated by ruleuler-admin npm run export:functionmap. DO NOT EDIT.',
    cases: EXEC_CASES.map((c) => ({
      rea: c.rea,
      position: c.position,
      xml: compile(c),
      ...(c.facts ? { facts: c.facts } : {}),
      ...(c.path ? { path: c.path } : {}),
      assert: c.assert,
    })),
  };
  return JSON.stringify(exported, null, 2) + '\n';
}

/** 配对表函数数（不含自定义），供测试对齐用 */
export const BUILTIN_FUNC_COUNT = allFuncs().length;
