package com.caritasem.ruleuler.server.controller;

// Feature: autotest-v2, Property 19: 用例包 source_type 正确性
// Feature: autotest-v2, Property 20: 文件导入用例数一致性
// Feature: autotest-v2, Property 21: 非法文件导入快速失败
// Validates: Requirements 3.7, 3.8, 9.1, 9.2, 9.3

import com.caritasem.ruleuler.console.servlet.respackage.autotest.TestCasePack;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;
import net.jqwik.api.*;
import net.jqwik.api.Tuple.Tuple2;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

import static org.junit.jupiter.api.Assertions.*;

/**
 * 手动导入属性测试。
 * 纯逻辑验证，不依赖 Spring 容器和数据库。
 */
class ManualImportPropertyTest {

    // =====================================================================
    // Property 19: 用例包 source_type 正确性
    // =====================================================================

    /**
     * Feature: autotest-v2, Property 19: 用例包 source_type 正确性
     * **Validates: Requirements 3.7, 3.8**
     */
    @Property(tries = 100)
    void autoGeneratedPackHasSourceTypeAuto(
            @ForAll("packName") String packName,
            @ForAll("positiveInt") int totalCases
    ) {
        TestCasePack pack = new TestCasePack();
        pack.setPackName(packName);
        pack.setSourceType("auto");
        pack.setTotalCases(totalCases);

        assertEquals("auto", pack.getSourceType(),
                "自动生成的用例包 source_type 必须为 auto");
    }

    @Property(tries = 100)
    void manualImportedPackHasSourceTypeManual(
            @ForAll("packName") String packName,
            @ForAll("positiveInt") int totalCases
    ) {
        TestCasePack pack = new TestCasePack();
        pack.setPackName("手动导入_" + packName);
        pack.setSourceType("manual");
        pack.setTotalCases(totalCases);

        assertEquals("manual", pack.getSourceType(),
                "手动导入的用例包 source_type 必须为 manual");
    }

    @Property(tries = 100)
    void sourceTypeMustBeAutoOrManual(
            @ForAll("creationMethod") String method
    ) {
        String sourceType = "auto".equals(method) ? "auto" : "manual";
        assertTrue("auto".equals(sourceType) || "manual".equals(sourceType),
                "source_type 只能是 auto 或 manual，实际=" + sourceType);
    }

    // =====================================================================
    // Property 20: 文件导入用例数一致性
    // =====================================================================

    /**
     * Feature: autotest-v2, Property 20: 文件导入用例数一致性
     * **Validates: Requirements 9.1, 9.2**
     */
    @Property(tries = 100)
    void csvImportCaseCountMatchesDataRows(
            @ForAll("validCsvData") Tuple2<String[], List<String[]>> csvData
    ) {
        String[] headers = csvData.get1();
        List<String[]> dataRows = csvData.get2();

        String csvContent = buildCsvContent(headers, dataRows);
        List<Map<String, Object>> rows = parseCsvContent(csvContent);

        assertEquals(dataRows.size(), rows.size(),
                "CSV 导入用例数应等于数据行数（不含表头）");

        TestCasePack pack = new TestCasePack();
        pack.setSourceType("manual");
        pack.setTotalCases(rows.size());

        assertEquals(dataRows.size(), pack.getTotalCases(),
                "用例包 total_cases 应等于数据行数 N=" + dataRows.size());
    }

    /**
     * Feature: autotest-v2, Property 20: 文件导入用例数一致性
     * **Validates: Requirements 9.1, 9.2**
     */
    @Property(tries = 100)
    void jsonImportCaseCountMatchesArraySize(
            @ForAll("validJsonArray") List<Map<String, Object>> jsonArray
    ) {
        int expectedCount = jsonArray.size();

        ObjectMapper mapper = new ObjectMapper();
        List<Map<String, Object>> parsed;
        try {
            String jsonStr = mapper.writeValueAsString(jsonArray);
            parsed = mapper.readValue(jsonStr, new TypeReference<>() {});
        } catch (Exception e) {
            fail("合法 JSON 序列化/反序列化不应失败: " + e.getMessage());
            return;
        }

        assertEquals(expectedCount, parsed.size(),
                "JSON 导入用例数应等于数组元素数");

        TestCasePack pack = new TestCasePack();
        pack.setSourceType("manual");
        pack.setTotalCases(parsed.size());

        assertEquals(expectedCount, pack.getTotalCases(),
                "用例包 total_cases 应等于 JSON 数组元素数 N=" + expectedCount);
    }

    // =====================================================================
    // Property 21: 非法文件导入快速失败
    // =====================================================================

    @Property(tries = 100)
    void invalidCsvColumnMismatchThrows(
            @ForAll("csvHeadersOnly") String[] headers,
            @ForAll("mismatchedRowValues") String[] badRow
    ) {
        Assume.that(badRow.length != headers.length);

        String csvContent = String.join(",", headers) + "\n" + String.join(",", badRow);

        assertThrows(RuntimeException.class, () -> parseCsvContent(csvContent),
                "列数不匹配的 CSV 应抛出异常");
    }

    @Property(tries = 100)
    void emptyCsvHeaderThrows(
            @ForAll("emptyHeaderCsv") String csvContent
    ) {
        assertThrows(RuntimeException.class, () -> parseCsvContent(csvContent),
                "空表头 CSV 应抛出异常");
    }

    @Property(tries = 100)
    void invalidJsonThrows(
            @ForAll("invalidJsonContent") String jsonContent
    ) {
        assertThrows(RuntimeException.class, () -> parseJsonContent(jsonContent),
                "非法 JSON 应抛出异常");
    }

    // =====================================================================
    // Providers
    // =====================================================================

    @Provide
    Arbitrary<String> packName() {
        return Arbitraries.strings().alpha().ofMinLength(1).ofMaxLength(20);
    }

    @Provide
    Arbitrary<Integer> positiveInt() {
        return Arbitraries.integers().between(1, 1000);
    }

    @Provide
    Arbitrary<String> creationMethod() {
        return Arbitraries.of("auto", "manual");
    }

    @Provide
    Arbitrary<Tuple2<String[], List<String[]>>> validCsvData() {
        Arbitrary<Integer> colCount = Arbitraries.integers().between(1, 5);
        return colCount.flatMap(cols -> {
            Arbitrary<String[]> headers = Arbitraries.strings().alpha()
                    .ofMinLength(1).ofMaxLength(8)
                    .array(String[].class).ofSize(cols);
            Arbitrary<String[]> row = Arbitraries.strings().alpha()
                    .ofMinLength(1).ofMaxLength(10)
                    .array(String[].class).ofSize(cols);
            Arbitrary<List<String[]>> rows = row.list().ofMinSize(1).ofMaxSize(20);
            return Combinators.combine(headers, rows).as(Tuple::of);
        });
    }

    @Provide
    Arbitrary<List<Map<String, Object>>> validJsonArray() {
        Arbitrary<String> key = Arbitraries.strings().alpha().ofMinLength(1).ofMaxLength(8);
        Arbitrary<Object> value = Arbitraries.oneOf(
                Arbitraries.integers().between(0, 999).map(i -> (Object) i),
                Arbitraries.strings().alpha().ofMinLength(1).ofMaxLength(10).map(s -> (Object) s)
        );
        Arbitrary<Map<String, Object>> entry = Combinators.combine(
                key.set().ofMinSize(1).ofMaxSize(4), value.list().ofMinSize(1).ofMaxSize(4)
        ).as((keys, vals) -> {
            Map<String, Object> m = new LinkedHashMap<>();
            Iterator<String> ki = keys.iterator();
            Iterator<Object> vi = vals.iterator();
            while (ki.hasNext() && vi.hasNext()) {
                m.put(ki.next(), vi.next());
            }
            return m;
        });
        return entry.list().ofMinSize(1).ofMaxSize(20);
    }

    @Provide
    Arbitrary<String[]> csvHeadersOnly() {
        return Arbitraries.strings().alpha().ofMinLength(1).ofMaxLength(6)
                .array(String[].class).ofMinSize(2).ofMaxSize(5);
    }

    @Provide
    Arbitrary<String[]> mismatchedRowValues() {
        return Arbitraries.strings().alpha().ofMinLength(1).ofMaxLength(6)
                .array(String[].class).ofMinSize(1).ofMaxSize(8);
    }

    @Provide
    Arbitrary<String> emptyHeaderCsv() {
        return Arbitraries.of(
                "",
                "   ",
                "\n",
                " \ndata1,data2"
        );
    }

    @Provide
    Arbitrary<String> invalidJsonContent() {
        return Arbitraries.of(
                "not json at all",
                "{\"key\":\"value\"}",
                "123",
                "\"just a string\"",
                "[null]",
                "[{}]",
                "[{\"a\":1}, {}]",
                "[{\"a\":1}, null]"
        );
    }

    // =====================================================================
    // 解析逻辑（复制自 AutoTestController，用于纯逻辑测试）
    // =====================================================================

    private static String buildCsvContent(String[] headers, List<String[]> dataRows) {
        StringBuilder sb = new StringBuilder();
        sb.append(String.join(",", headers)).append("\n");
        for (String[] row : dataRows) {
            sb.append(String.join(",", row)).append("\n");
        }
        return sb.toString();
    }

    private static List<Map<String, Object>> parseCsvContent(String content) {
        List<Map<String, Object>> rows = new ArrayList<>();
        try (BufferedReader reader = new BufferedReader(
                new InputStreamReader(
                        new ByteArrayInputStream(content.getBytes(StandardCharsets.UTF_8)),
                        StandardCharsets.UTF_8))) {
            String headerLine = reader.readLine();
            if (headerLine == null || headerLine.isBlank()) {
                throw new RuntimeException("CSV 文件为空或缺少表头");
            }
            String[] headers = headerLine.split(",", -1);
            for (int i = 0; i < headers.length; i++) {
                headers[i] = headers[i].trim();
                if (headers[i].isEmpty()) {
                    throw new RuntimeException("CSV 表头第 " + (i + 1) + " 列为空");
                }
            }

            String line;
            int lineNum = 1;
            while ((line = reader.readLine()) != null) {
                lineNum++;
                if (line.isBlank()) continue;
                String[] values = line.split(",", -1);
                if (values.length != headers.length) {
                    throw new RuntimeException("CSV 第 " + lineNum + " 行列数("
                            + values.length + ")与表头列数(" + headers.length + ")不匹配");
                }
                Map<String, Object> row = new LinkedHashMap<>();
                for (int i = 0; i < headers.length; i++) {
                    row.put(headers[i], values[i].trim());
                }
                rows.add(row);
            }
        } catch (RuntimeException e) {
            throw e;
        } catch (Exception e) {
            throw new RuntimeException("CSV 解析失败: " + e.getMessage());
        }
        return rows;
    }

    private static List<Map<String, Object>> parseJsonContent(String content) {
        ObjectMapper mapper = new ObjectMapper();
        try {
            List<Map<String, Object>> rows = mapper.readValue(
                    content, new TypeReference<List<Map<String, Object>>>() {});
            for (int i = 0; i < rows.size(); i++) {
                Map<String, Object> row = rows.get(i);
                if (row == null || row.isEmpty()) {
                    throw new RuntimeException("JSON 第 " + (i + 1) + " 个元素为空对象");
                }
            }
            return rows;
        } catch (RuntimeException e) {
            throw e;
        } catch (Exception e) {
            throw new RuntimeException("JSON 解析失败: " + e.getMessage());
        }
    }
}
