spring:
  profiles:
    active: @profileActive@
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

ruleuler:
  function-jar:
    max-size-bytes: 20971520
    max-entries: 2000
    max-uncompressed-xml-bytes: 1048576


logging:
  file:
    path: logs
    name-suffix: server

